"""Record and verify the provenance of a training corpus.

A corpus is only as trustworthy as the engine that labelled it, and that
engine is a moving target: haVoc's evaluation changes, its search changes, and
a `.hbin` on disk carries no memory of which version wrote it. Six months from
now "why is this net worse than the old one" is unanswerable if the data
cannot be traced to a commit. So every artefact gets a `.meta.json` sidecar
naming the commit, the command, and a checksum.

Provenance comes in two grades and the sidecar says which one it has:

  attributed   The commit is inferred -- usually from the build timestamp of
               the binary that wrote the file. Good enough to navigate by, not
               good enough to bet on.

  verified     The claim was *reproduced*. For a deterministic label (the HCE
               static evaluation) this is exact: re-label a sample with a build
               of the named commit and require every score to match. A search
               label cannot be verified this way, because it depends on time
               and thread count, so search corpora stay attributed.

Usage:
    provenance.py stamp FILE --commit HASH --grade attributed --note "..."
    provenance.py verify FILE          # checksum still matches the sidecar
    provenance.py manifest DIR         # render MANIFEST.md from the sidecars
"""

from __future__ import annotations

import argparse
import datetime as _dt
import hashlib
import json
import os
import subprocess
import sys


def sha256(path: str, chunk: int = 1 << 22) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        while True:
            b = f.read(chunk)
            if not b:
                break
            h.update(b)
    return h.hexdigest()


def sidecar_path(path: str) -> str:
    return path + ".meta.json"


def record_count(path: str) -> int | None:
    """Records in a .hbin, from its size. The header is 64 bytes, records 128."""
    if not path.endswith(".hbin"):
        return None
    n = os.path.getsize(path) - 64
    return n // 128 if n > 0 and n % 128 == 0 else None


def git(*args: str) -> str:
    try:
        return subprocess.check_output(["git", *args], stderr=subprocess.DEVNULL).decode().strip()
    except Exception:
        return ""


def stamp(args: argparse.Namespace) -> int:
    path = os.path.abspath(args.file)
    meta = {
        "file": os.path.basename(path),
        "bytes": os.path.getsize(path),
        "sha256": sha256(path),
        "records": record_count(path),
        "engine_commit": args.commit,
        "provenance_grade": args.grade,
        "label": args.label,
        "command": args.command,
        "note": args.note,
        "stamped_utc": _dt.datetime.now(_dt.timezone.utc).isoformat(timespec="seconds"),
        "stamped_by_repo_head": git("rev-parse", "HEAD"),
    }
    with open(sidecar_path(path), "w") as f:
        json.dump(meta, f, indent=2)
        f.write("\n")
    print(f"stamped {sidecar_path(path)}  ({meta['sha256'][:12]}, {meta['bytes']:,} bytes)")
    return 0


def verify(args: argparse.Namespace) -> int:
    path = os.path.abspath(args.file)
    sc = sidecar_path(path)
    if not os.path.exists(sc):
        print(f"{path}: no sidecar; provenance unknown")
        return 1
    meta = json.load(open(sc))
    bad = []
    if os.path.getsize(path) != meta["bytes"]:
        bad.append(f"size {os.path.getsize(path):,} != recorded {meta['bytes']:,}")
    else:
        got = sha256(path)
        if got != meta["sha256"]:
            bad.append(f"sha256 {got[:12]} != recorded {meta['sha256'][:12]}")
    if bad:
        print(f"{os.path.basename(path)}: CHANGED SINCE STAMPING -- " + "; ".join(bad))
        return 1
    print(
        f"{os.path.basename(path)}: intact, {meta['provenance_grade']} to "
        f"{meta['engine_commit']}"
    )
    return 0


def manifest(args: argparse.Namespace) -> int:
    root = os.path.abspath(args.dir)
    rows = []
    for dirpath, _, files in os.walk(root):
        for name in sorted(files):
            if not name.endswith(".meta.json"):
                continue
            meta = json.load(open(os.path.join(dirpath, name)))
            rel = os.path.relpath(os.path.join(dirpath, name[: -len(".meta.json")]), root)
            rows.append((rel, meta))
    rows.sort()

    out = [
        "# haVoc training data",
        "",
        "Generated by `scripts/nnue/provenance.py manifest`. Do not edit by hand;",
        "edit the `.meta.json` sidecars and re-render.",
        "",
        "`verified` means the labels were reproduced under the named commit and",
        "matched exactly. `attributed` means the commit is inferred, normally from",
        "the build timestamp of the binary that wrote the file.",
        "",
        "| file | records | size | label | commit | grade |",
        "|---|---|---|---|---|---|",
    ]
    for rel, m in rows:
        recs = f"{m['records']:,}" if m.get("records") else "-"
        size = f"{m['bytes'] / 1e6:.0f} MB"
        out.append(
            f"| `{rel}` | {recs} | {size} | {m.get('label') or '-'} | "
            f"`{(m.get('engine_commit') or '?')[:7]}` | {m.get('provenance_grade')} |"
        )
    out += ["", "## Notes", ""]
    for rel, m in rows:
        if m.get("note"):
            out.append(f"- **`{rel}`** -- {m['note']}")
    if any(m.get("command") for _, m in rows):
        out += ["", "## Commands", ""]
        for rel, m in rows:
            if m.get("command"):
                out.append(f"- `{rel}`:\n  ```\n  {m['command']}\n  ```")
    out.append("")

    dest = os.path.join(root, "MANIFEST.md")
    with open(dest, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {dest} ({len(rows)} artefacts)")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    sub = ap.add_subparsers(dest="cmd", required=True)

    s = sub.add_parser("stamp")
    s.add_argument("file")
    s.add_argument("--commit", required=True)
    s.add_argument("--grade", choices=["attributed", "verified"], default="attributed")
    s.add_argument("--label", default=None)
    s.add_argument("--command", default=None)
    s.add_argument("--note", default=None)
    s.set_defaults(fn=stamp)

    v = sub.add_parser("verify")
    v.add_argument("file")
    v.set_defaults(fn=verify)

    m = sub.add_parser("manifest")
    m.add_argument("dir")
    m.set_defaults(fn=manifest)

    args = ap.parse_args()
    return args.fn(args)


if __name__ == "__main__":
    sys.exit(main())
