# Writes build_info.hpp with the commit the binary was built from.
#
# Run as a script at *build* time, not at configure time: a configure-time
# hash goes stale the moment you commit, and a stale hash on a training corpus
# is worse than no hash at all, because it looks authoritative. The file is
# rewritten only when the contents change, so this does not force a rebuild on
# every invocation.
#
# Expects HAVOC_GIT_DIR and HAVOC_OUTPUT to be set with -D.

set(commit "unknown")
set(dirty "false")

find_package(Git QUIET)
if(Git_FOUND)
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" rev-parse HEAD
        WORKING_DIRECTORY "${HAVOC_GIT_DIR}"
        OUTPUT_VARIABLE out
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
        RESULT_VARIABLE rc)
    if(rc EQUAL 0 AND out)
        set(commit "${out}")
        # A dirty tree means the binary does not correspond to any commit, and
        # anything it labels has to say so.
        execute_process(
            COMMAND "${GIT_EXECUTABLE}" status --porcelain --untracked-files=no
            WORKING_DIRECTORY "${HAVOC_GIT_DIR}"
            OUTPUT_VARIABLE status_out
            ERROR_QUIET
            RESULT_VARIABLE status_rc)
        if(status_rc EQUAL 0 AND NOT status_out STREQUAL "")
            set(dirty "true")
        endif()
    endif()
endif()

set(content "#pragma once
// Generated by cmake/GitInfo.cmake. Do not edit.
#include <string_view>
namespace havoc {
inline constexpr std::string_view GIT_COMMIT = \"${commit}\";
inline constexpr bool GIT_DIRTY = ${dirty};
}  // namespace havoc
")

set(existing "")
if(EXISTS "${HAVOC_OUTPUT}")
    file(READ "${HAVOC_OUTPUT}" existing)
endif()
if(NOT existing STREQUAL content)
    file(WRITE "${HAVOC_OUTPUT}" "${content}")
endif()
