#!/usr/bin/env python3
"""SPSA over engine parameters, with games as the objective.

Every other objective tried in this repository has misled. Bench node count is
non-monotonic in the search margins, and the Texel error is independent of the
parameter values it is supposed to be fitting (see docs/roadmap.md section 5).
Game results are the only signal that has held up, so this optimises them
directly.

Simultaneous Perturbation Stochastic Approximation needs exactly two objective
measurements per iteration regardless of how many parameters are being tuned,
which is what makes a games-based objective affordable at all. The two
measurements are obtained from a single head-to-head match: perturb every
parameter at once by +c*delta and by -c*delta, then play those two parameter
sets against each other. The match score *is* the difference between the two
measurements, so one match yields the whole gradient estimate.

Both sides are the same binary. Only the parameter file differs, so no code
delta can leak into the comparison.

Usage:

    spsa.py --engine build/havoc \\
            --param king_shelter_0=-15:-60:20 \\
            --param king_shelter_1=7:-30:40 \\
            --param king_shelter_2=1:-30:40 \\
            --param king_shelter_3=-4:-40:30 \\
            --iterations 60 --games-per-iter 32 --tag shelter

State is written after every iteration and --resume picks it back up. This
machine has a history of hard lockups under sustained load; an optimiser that
loses a night of games to one is not much use.
"""

import argparse
import json
import os
import random
import re
import shutil
import subprocess
import sys
import time

SCORE_RE = re.compile(r"^Score of .*?: (\d+) - (\d+) - (\d+)\s+\[([0-9.]+)\]", re.M)


class Param:
    __slots__ = ("name", "value", "lo", "hi", "a")

    def __init__(self, name, value, lo, hi):
        self.name = name
        self.value = float(value)
        self.lo = float(lo)
        self.hi = float(hi)
        self.a = 0.0

    def clipped(self, v):
        return max(self.lo, min(self.hi, v))

    @property
    def span(self):
        return self.hi - self.lo


def parse_param(spec):
    """name=init:lo:hi"""
    try:
        name, rest = spec.split("=", 1)
        init, lo, hi = rest.split(":")
        return Param(name.strip(), float(init), float(lo), float(hi))
    except ValueError:
        raise argparse.ArgumentTypeError(
            f"bad --param {spec!r}, expected name=init:lo:hi")


def write_params(path, params, values):
    with open(path, "w") as fh:
        fh.write("# generated by spsa.py -- do not edit\n")
        for p, v in zip(params, values):
            fh.write(f"{p.name} = {int(round(v))}\n")


def play_match(cutechess, engine, pf_a, pf_b, games, tc, book, concurrency,
               pgnout=None, eval_file=None):
    """Head-to-head between two parameter files. Returns A's score rate.

    -repeat plays every opening twice with the colours reversed, which pairs
    the samples and removes the opening's contribution to the variance. That
    matters more here than in an SPRT: the gradient estimate is a difference of
    two noisy scores, so unpaired noise enters it twice.
    """
    cmd = [
        cutechess,
        "-engine", f"cmd={engine}", "name=a", f"option.ParamFile={pf_a}",
        "-engine", f"cmd={engine}", "name=b", f"option.ParamFile={pf_b}",
        "-each", "proto=uci", f"tc={tc}", "option.Hash=64", "option.Threads=1",
        "timemargin=300",
    ]
    # Both sides, never one: this tunes search, so the evaluation has to be
    # identical across the comparison or the gradient picks up the eval
    # difference instead of the parameter perturbation. Search margins are
    # expressed in the eval's units and calibrated to its noise, so tuning them
    # against an evaluation the engine will not ship with tunes the wrong
    # thing.
    if eval_file:
        cmd += [f"option.EvalFile={eval_file}"]
    cmd += [
        "-openings", f"file={book}", "format=epd", "order=random",
        "-repeat", "-games", str(games), "-concurrency", str(concurrency),
        "-ratinginterval", str(games),
    ]
    if pgnout:
        cmd += ["-pgnout", pgnout]

    out = subprocess.run(cmd, capture_output=True, text=True).stdout
    matches = SCORE_RE.findall(out)
    if not matches:
        sys.stderr.write(out[-2000:])
        raise RuntimeError("could not parse a score out of cutechess")

    w, l, d, _ = matches[-1]
    w, l, d = int(w), int(l), int(d)
    n = w + l + d
    if n == 0:
        raise RuntimeError("match reported zero games")
    return (w + 0.5 * d) / n, w, l, d


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--engine", required=True)
    ap.add_argument("--param", action="append", required=True, type=parse_param,
                    dest="params", metavar="name=init:lo:hi")
    ap.add_argument("--iterations", type=int, default=60)
    ap.add_argument("--games-per-iter", type=int, default=32)
    ap.add_argument("--tc", default="10+0.1")
    ap.add_argument("--tag", required=True)
    ap.add_argument("--concurrency", type=int,
                    default=int(os.environ.get("CONC", 0)) or max(1, os.cpu_count() - 2))
    ap.add_argument("--book", default=os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "book.epd"))
    ap.add_argument("--cutechess", default=os.environ.get("CUTECHESS") or
                    shutil.which("cutechess-cli") or "cutechess-cli")
    ap.add_argument("--workdir", default=os.environ.get("HAVOC_WORK", "testruns"))
    # SPSA gains. The exponents are Spall's recommended asymptotically optimal
    # values. `c` is expressed as a fraction of each parameter's own range so
    # that one setting works across parameters of very different scale, and is
    # kept large enough that the perturbation is actually measurable in games.
    ap.add_argument("--c-frac", type=float, default=0.15,
                    help="initial perturbation as a fraction of each range")
    ap.add_argument("--a-frac", type=float, default=0.08,
                    help="range fraction moved in iteration 1 by a 100%% score")
    ap.add_argument("--alpha", type=float, default=0.602)
    ap.add_argument("--gamma", type=float, default=0.101)
    ap.add_argument("--eval-file", default=None,
                    help="Network to load on both sides. Search margins are in "
                         "the evaluation's units, so they must be tuned against "
                         "the evaluation that will ship.")
    ap.add_argument("--resume", action="store_true")
    ap.add_argument("--seed", type=int, default=None)
    args = ap.parse_args()

    os.makedirs(args.workdir, exist_ok=True)
    state_path = os.path.join(args.workdir, f"spsa-{args.tag}.json")
    log_path = os.path.join(args.workdir, f"spsa-{args.tag}.log")

    params = args.params
    start_iter = 1

    if args.resume and os.path.exists(state_path):
        with open(state_path) as fh:
            state = json.load(fh)
        saved = {p["name"]: p for p in state["params"]}
        for p in params:
            if p.name in saved:
                p.value = saved[p.name]["value"]
        start_iter = state["iteration"] + 1
        rng = random.Random(state.get("seed"))
        # Replay the consumed draws so the perturbation sequence is not reused.
        for _ in range((start_iter - 1) * len(params)):
            rng.random()
        print(f"resuming {args.tag} at iteration {start_iter}")
    else:
        seed = args.seed if args.seed is not None else random.randrange(1 << 30)
        rng = random.Random(seed)
        state = {"tag": args.tag, "seed": seed, "iteration": 0, "history": []}

    # A is the standard "stability constant": it keeps the first steps from
    # being the largest ones taken, which with a noisy games objective would
    # simply throw the starting point away.
    A = max(1.0, 0.10 * args.iterations)

    # The textbook update is theta += a_k * diff / (2 * c_k) * delta, so the
    # step depends on the perturbation size and `a` cannot be chosen without
    # reference to `c`. Deriving it from an interpretable quantity instead: a
    # is fixed so that on iteration 1 a hypothetical 100%-0% match moves the
    # parameter by exactly --a-frac of its range. The 1/c_k scaling is retained
    # for later iterations, which is what makes the estimate a gradient rather
    # than a fixed-size step.
    #
    # Calibrating this by hand is not optional. With `a` set to "a fraction of
    # the range" directly, the division by 2*c_k left a full-signal iteration
    # moving a 80-wide parameter by 0.09 -- indistinguishable from not running.
    for p in params:
        c1 = args.c_frac * p.span
        p.a = args.a_frac * p.span * 2.0 * c1 * ((1.0 + A) ** args.alpha)

    log = open(log_path, "a", buffering=1)
    log.write(f"\n=== spsa {args.tag} started {time.ctime()} ===\n")
    log.write(f"engine={args.engine} tc={args.tc} games/iter={args.games_per_iter} "
              f"conc={args.concurrency}\n")
    log.write("params: " + ", ".join(
        f"{p.name}={int(p.value)}[{int(p.lo)},{int(p.hi)}]" for p in params) + "\n")

    pf_plus = os.path.join(args.workdir, f"spsa-{args.tag}-plus.params")
    pf_minus = os.path.join(args.workdir, f"spsa-{args.tag}-minus.params")

    for k in range(start_iter, args.iterations + 1):
        ck_scale = 1.0 / (k ** args.gamma)
        ak_scale = 1.0 / ((k + A) ** args.alpha)

        deltas = [rng.choice((-1.0, 1.0)) for _ in params]
        plus, minus, cks = [], [], []
        for p, d in zip(params, deltas):
            ck = args.c_frac * p.span * ck_scale
            cks.append(ck)
            plus.append(p.clipped(p.value + ck * d))
            minus.append(p.clipped(p.value - ck * d))

        write_params(pf_plus, params, plus)
        write_params(pf_minus, params, minus)

        t0 = time.time()
        score, w, l, d = play_match(
            args.cutechess, args.engine, pf_plus, pf_minus,
            args.games_per_iter, args.tc, args.book, args.concurrency,
            eval_file=args.eval_file)
        dt = time.time() - t0

        # y(+) - y(-) as measured directly by the head-to-head score.
        diff = 2.0 * score - 1.0
        for i, (p, delta) in enumerate(zip(params, deltas)):
            # Central-difference SPSA estimate. delta is +-1 so 1/delta == delta.
            g = diff * delta / (2.0 * cks[i])
            ak = p.a * ak_scale
            p.value = p.clipped(p.value + ak * g)

        state["iteration"] = k
        state["params"] = [{"name": p.name, "value": p.value,
                            "lo": p.lo, "hi": p.hi} for p in params]
        state["history"].append(
            {"iter": k, "score": score, "w": w, "l": l, "d": d,
             "values": {p.name: int(round(p.value)) for p in params}})
        tmp = state_path + ".tmp"
        with open(tmp, "w") as fh:
            json.dump(state, fh, indent=1)
        os.replace(tmp, state_path)

        line = (f"iter {k:3d}/{args.iterations}  +{w}/-{l}/={d}  "
                f"score={score:.3f}  {dt:5.0f}s  " +
                " ".join(f"{p.name}={int(round(p.value))}" for p in params))
        print(line)
        log.write(line + "\n")

    final = os.path.join(args.workdir, f"spsa-{args.tag}-final.params")
    write_params(final, params, [p.value for p in params])
    log.write(f"final written to {final}\n")
    print(f"\nfinal parameters: {final}")
    print("This is a starting point, not a result. SPRT it against the "
          "compiled-in defaults with sprt-paramfile.sh before believing it.")


if __name__ == "__main__":
    main()
